### PR TITLE
Wrap parsing of throttling response in try block to avoid errors

### PR DESCRIPTION
**Pull request by isaachier**
Signed-off-by: Isaac Hier <ihier@uber.com>

(internal ref T2245255)

### CODE REVIEW

**Comment by isaachier** [comment]
Have these tests been failing until recently?

**Comment by yurishkuro** [comment]
the crossdock seems to have a hard time since recently, but the unit tests failures I haven't seen before, they look more like linter issues, probably because of a new linter release (we should really be pinning those tools)

**Comment by yurishkuro** [comment]
trying to fix crossdock tests in #222

**Comment by isaachier** [comment]
Looks good now. Awaiting approval.

**Pull request merged**
