### PR TITLE
Add tests for unicode tag keys and values

### PR DESCRIPTION
**Pull request by SEJeff**
Who doesn't love an excuse to put 💩 into code?

Refs: #22

### CODE REVIEW

**Comment by SEJeff** [comment]
Not sure if this covers 100% of what you were looking for @yurishkuro, but it seems like a great start!

**Comment by SEJeff** [comment]
The coding line at the top is mandatory, otherwise the test runner blows up:

```
==================================================================================== ERRORS ====================================================================================
____________________________________________________________________ ERROR collecting tests/test_config.py _____________________________________________________________________
ve/lib/python2.7/site-packages/_pytest/python.py:611: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
ve/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/home/jeff/git/jaeger-client-python/tests/test_config.py", line 40
E   SyntaxError: Non-ASCII character '\xf0' in file /home/jeff/git/jaeger-client-python/tests/test_config.py on line 40, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
=========================================================================== 1 error in 0.11 seconds ============================================================================
```

**Comment by SEJeff** [comment]
Go home coveralls, you're drunk!

**Comment by SEJeff** [comment]
@yurishkuro yeah I wasn't really sure what in specific you wanted me to test for. Happy to take a stab at whatever else needs to be done. I'll try to see if I can't work on it tonight or one night this week (if no one else beats me to it!).

**Comment by yurishkuro** [comment]
closing for inactivity

**Pull request closed without merging**
