### PR TITLE
Ensure Tracer.close() flushes finished spans

### PR DESCRIPTION
**Pull request by obataku**
* assigning to Reporter._stopped in _flush() instead of close() avoids dropping those spans passed to report_span just _prior_ to Reporter.close() for which _report_span_from_ioloop will execute only *afterwards*; this way those scheduled callbacks will get a chance to run before _flush stops the reporter and those pending spans make it into the queue before the reporter shuts down.

Signed-off-by: obataku <19821199+obataku@users.noreply.github.com>

## Which problem is this PR solving?
this PR stops `Reporter.close()` from dropping spans whose background `_report_span_from_ioloop` callbacks are still pending execution; see #50 & #246

### CODE REVIEW

**Comment by obataku** [comment]
I broke out the `Reporter.close()` fix from my draft PR #293

**Comment by yurishkuro** [comment]
We need to fix #295 to ensure that all tests run.

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
Thanks, @obataku. Do you think this resolves #50?

**Comment by obataku** [comment]
@yurishkuro it _should_ resolve #50 so long as you `yield`/`await` the resultant `Future` in the context of the same IO/event loop as the tracer and are only concerned with flushing all spans `finish()`-ed prior to `close()`, i.e.
```py
tracer = Config(...).initialize_tracer(io_loop=IOLoop.current())
with tracer.start_active_span('foo'):
    ...
await tracer.close()
```

**Pull request merged**
